name: Deploy to Web Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy test.html to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "hehe.html"
          target: "/var/www/html"
          overwrite: true
          # strip_components: 0 (default) or 1?
          # Since index.html is in the root, it will copy the file to /var/www/html/index.html